In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.tree import plot_tree
import joblib

In [3]:
data = pd.read_csv("dataset.csv")
data.head()

,Index,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
0,0,23.7000,26.272,585.200000,749.200000,0.004764,1.0
1,1,23.7180,26.290,578.400000,760.400000,0.004773,1.0
2,2,23.7300,26.230,572.666667,769.666667,0.004765,1.0
3,3,23.7225,26.125,493.750000,774.750000,0.004744,1.0
4,4,23.7540,26.200,488.600000,779.000000,0.004767,1.0

In [4]:
data.describe()

,Index,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
count,2671.000000,2671.000000,2671.000000,2671.000000,2671.000000,2671.000000,2665.000000
mean,1335.000000,21.439083,25.355957,194.023637,718.022667,0.004029,0.364728
std,771.195609,1.032718,2.434476,250.503102,292.363657,0.000611,0.481444
min,0.000000,20.200000,22.100000,0.000000,427.500000,0.003303,0.000000
25%,667.500000,20.650000,23.278750,0.000000,466.000000,0.003532,0.000000
50%,1335.000000,20.890000,25.000000,0.000000,581.600000,0.003815,0.000000
75%,2002.500000,22.390000,26.826667,443.400000,955.458333,0.004534,1.000000
max,2670.000000,24.408333,31.472500,1697.250000,1402.250000,0.005378,1.000000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2671 entries, 0 to 2670
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          2671 non-null   int64
 1   Temperature    2671 non-null   float64
 2   Humidity       2671 non-null   float64
 3   Light          2671 non-null   float64
 4   CO2            2671 non-null   float64
 5   HumidityRatio  2671 non-null   float64
 6   Occupancy      2665 non-null   float64
dtypes: float64(6), int64(1)
memory usage: 146.2 KB

In [6]:
data.isnull().sum()

Index            0
Temperature      0
Humidity         0
Light            0
CO2              0
HumidityRatio    0
Occupancy        6
dtype: int64

In [8]:
data = data.dropna(subset=["Occupancy"])

In [14]:
X = data[["Temperature", "Humidity", "Light", "CO2", "HumidityRatio"]]
y = data["Occupancy"]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [17]:
model_all = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

model_all.fit(X_train, y_train)

y_pred_all = model_all.predict(X_test)

print("=== Model A: All Features ===")
print("Accuracy:", accuracy_score(y_test, y_pred_all))
print(classification_report(y_test, y_pred_all))

=== Model A: All Features ===
Accuracy: 0.9868667917448405
              precision    recall  f1-score   support

         0.0       0.99      0.99      0.99       339
         1.0       0.97      0.99      0.98       194

    accuracy                           0.99       533
   macro avg       0.98      0.99      0.99       533
weighted avg       0.99      0.99      0.99       533

In [ ]:
feature_names = X.columns.tolist()
joblib.dump((model_all, feature_names), "occupancy_model.pkl")

NameError: name 'model' is not defined